module.exports = {
  docs: [
    {
      type: "category",
      label: "Start here",
      collapsed: false,
      items: ["intro", "install", "hello-world", "mental-model"],
    },
    {
      type: "category",
      label: "The language",
      collapsed: false,
      items: [
        "files",
        "types",
        "operators",
        "variables",
        "functions",
        "control-flow",
        "collections",
        "oop",
        "io",
        "roblox",
      ],
    },
    {
      type: "category",
      label: "Modern syntax",
      collapsed: false,
      items: [
        "observables-signals",
        "guard-match",
        "concurrency",
        "attributes",
      ],
    },
    {
      type: "category",
      label: "UI & advanced",
      collapsed: false,
      items: [
        "ui-fusion",
        "ui-vide",
        "advanced-types",
        "advanced-patterns",
      ],
    },
    {
      type: "category",
      label: "Language reference",
      collapsed: false,
      items: [
        "reference",
        {
          type: "category",
          label: "I/O",
          collapsed: true,
          items: [
            "reference/post",
            "reference/warn",
            "reference/report",
            "reference/cout",
          ],
        },
        {
          type: "category",
          label: "Builtins",
          collapsed: true,
          items: [
            "reference/GetService",
            "reference/pcall",
            "reference/new",
            "reference/static_cast",
            "reference/string_concat",
            "reference/to_string",
            "reference/to_number",
            "reference/to_bool",
            "reference/null",
            "reference/init",
            "reference/this",
          ],
        },
        {
          type: "category",
          label: "Types",
          collapsed: true,
          items: [
            "reference/int",
            "reference/float",
            "reference/double",
            "reference/bool",
            "reference/string",
            "reference/void",
            "reference/func",
            "reference/auto",
            "reference/optional",
            "reference/array",
            "reference/vector",
            "reference/dictionary",
            "reference/instance-pointer",
            "reference/const",
            "reference/signal-type",
            "reference/observable",
          ],
        },
        {
          type: "category",
          label: "Operators",
          collapsed: true,
          items: [
            "reference/operator-method",
            "reference/operator-table",
            "reference/operator-property",
            "reference/operator-concat",
            "reference/operator-janitor",
            "reference/operator-arithmetic",
            "reference/operator-comparison",
            "reference/operator-logic",
            "reference/operator-assignment",
            "reference/operator-increment",
            "reference/operator-designated",
          ],
        },
        {
          type: "category",
          label: "Control flow",
          collapsed: true,
          items: [
            "reference/if",
            "reference/while",
            "reference/for",
            "reference/range-for",
            "reference/switch",
            "reference/guard",
            "reference/match",
            "reference/break",
            "reference/return",
          ],
        },
        {
          type: "category",
          label: "Functions & OOP",
          collapsed: true,
          items: [
            "reference/function",
            "reference/lambda",
            "reference/struct",
            "reference/class-method",
            "reference/access-labels",
          ],
        },
        {
          type: "category",
          label: "Signals",
          collapsed: true,
          items: [
            "reference/Fire",
            "reference/Connect",
            "reference/Once",
            "reference/Wait",
            "reference/GetPropertyChangedSignal",
            "reference/OnChange",
          ],
        },
        {
          type: "category",
          label: "Concurrency",
          collapsed: true,
          items: [
            "reference/async",
            "reference/await",
            "reference/spawn",
            "reference/parallel",
            "reference/destructure",
          ],
        },
        {
          type: "category",
          label: "Attributes & preprocessor",
          collapsed: true,
          items: [
            "reference/attr-server",
            "reference/attr-client",
            "reference/include",
            "reference/pragma-strict",
            "reference/pragma-nstrict",
            "reference/pragma-native",
            "reference/pragma-optimize",
            "reference/pragma-once",
          ],
        },
        {
          type: "category",
          label: "Headers",
          collapsed: true,
          items: [
            "reference/header-roblox",
            "reference/header-instances",
            "reference/header-datatypes",
            "reference/header-janitor",
            "reference/header-dataservice",
          ],
        },
        "reference/language-id",
      ],
    },
    {
      type: "category",
      label: "Spec & extras",
      items: [
        "cheatsheet",
        "unsupported",
        "cluaupp",
        "cluaupp-callbacks",
        "spec/syntax",
        "spec/emit",
        "spec/types",
        "spec/files",
      ],
    },
  ],
};
