function(clpp_apply_sanitizers target)
  if(NOT CLPP_SANITIZE_ADDRESS)
    return()
  endif()

  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -fsanitize=address)
  elseif(MSVC)
    target_compile_options(${target} PRIVATE /fsanitize=address)
  else()
    message(WARNING "AddressSanitizer not supported for ${CMAKE_CXX_COMPILER_ID}")
  endif()
endfunction()
